const fresh=()=>({hp:100,rei:60,xp:0,race:'',weapon:'',allies:[],log:[]});let state=fresh();
		const scenes={
			start:{chapter:'Prólogo · A noite sem estrelas',title:'O sino que ninguém ouviu',text:'A chuva cai para cima em Kurohama. No meio da estação vazia, uma criatura mascarada fareja as lembranças dos passageiros — e uma rachadura azul rasga o céu.\n\nUma voz ecoa dentro de você: “Escolha o que vai proteger, antes que escolha por você.”',choices:[
				{label:'“Serei a lâmina entre os mundos.”',detail:'Vigia: disciplina, espada e juramento.',next:'vigia',effect:{race:'Vigia',weapon:'Kirisame · lâmina do limiar',rei:10}},
				{label:'“A luz também pode ser uma arma.”',detail:'Tecelão: arcos de energia e precisão.',next:'tecelao',effect:{race:'Tecelão',weapon:'Arco de Éter · fio de aurora',rei:20}},
				{label:'“Não vou negar a fera em mim.”',detail:'Errante: máscara, instinto e força brutal.',next:'errante',effect:{race:'Errante',weapon:'Garras do Eclipse · punhos vivos',hp:15,rei:-5}}
			]},
			vigia:{chapter:'Capítulo I · O despertar',title:'A lâmina tem um nome',text:'Uma espada negra surge na sua mão. A criatura avança, mas a lâmina sussurra: Kirisame. Cada golpe desenha um caminho na chuva suspensa.',choices:[{label:'Treinar o corte que divide o espaço.',detail:'Aprenda o Passo de Maré.',next:'treino',effect:{rei:-10,xp:1}},{label:'Retirar os feridos da estação.',detail:'Salvar vidas pode custar energia.',next:'resgate',effect:{hp:-8,xp:1}}]},
			tecelao:{chapter:'Capítulo I · O despertar',title:'Fios de luz na escuridão',text:'Um arco translúcido se forma entre seus dedos. Cada flecha é feita de lembranças que quase esqueceu. A criatura recua, mas a fenda no céu cresce.',choices:[{label:'Disparar uma salva contra a fenda.',detail:'Uma demonstração arriscada de precisão.',next:'treino',effect:{rei:-12,xp:1}},{label:'Erguer um escudo para os passageiros.',detail:'Proteja as pessoas primeiro.',next:'resgate',effect:{rei:-8,hp:5,xp:1}}]},
			errante:{chapter:'Capítulo I · O despertar',title:'A máscara por dentro',text:'Uma meia-máscara cobre seu rosto. A fera não é uma voz distante: é sua própria fome de sobreviver. A criatura mascarada hesita ao reconhecer algo familiar em você.',choices:[{label:'Aceitar a força e encarar a criatura.',detail:'Poder bruto, mas o esforço cobra seu preço.',next:'treino',effect:{hp:-12,rei:8,xp:1}},{label:'Conter o instinto e guiar os passageiros.',detail:'Prove que sua vontade é mais forte.',next:'resgate',effect:{hp:8,rei:-8,xp:1}}]},
			treino:{chapter:'Capítulo II · Ecos',title:'Uma aliada improvável',text:'No túnel, você encontra Nara, cartógrafa espiritual de lanterna rachada. Ela observa sua arma. “A criatura não está atacando a cidade. Está fugindo de alguma coisa.” Ao longe, a fenda pulsa como um coração.',choices:[{label:'Confiar em Nara e seguir os rastros.',detail:'Ganhe uma aliada e investigue a fenda.',next:'investigar',effect:{ally:'Nara',xp:1}},{label:'Exigir respostas antes de avançar.',detail:'Mantenha distância e recupere energia.',next:'confronto',effect:{rei:12}}]},
			resgate:{chapter:'Capítulo II · Ecos',title:'O preço de salvar',text:'Os passageiros escapam por uma saída lateral. Nara, uma cartógrafa espiritual, oferece sua lanterna rachada. “Ela aponta para aquilo que não deveria existir. E está apontando para nós.” A criatura sumiu nos túneis.',choices:[{label:'Aceitar a ajuda de Nara.',detail:'A lanterna revela caminhos ocultos.',next:'investigar',effect:{ally:'Nara',rei:5}},{label:'Seguir sozinho pelos trilhos.',detail:'Vá direto ao encontro do perigo.',next:'confronto',effect:{xp:1}}]},
			investigar:{chapter:'Capítulo III · A fenda',title:'O mapa de coisas perdidas',text:'A lanterna revela uma passagem sob a estação. Nas paredes, nomes apagados. Nara traduz o último: “Devorador de Ecos”. Nasceu das lembranças abandonadas pela cidade e está sendo puxado para a fenda. Do outro lado, alguém bate três vezes.',choices:[{label:'Responder ao chamado com sua energia.',detail:'Custa 20 de energia espiritual.',next:'portal',cost:{rei:20},effect:{xp:1}},{label:'Pedir que Nara feche a passagem.',detail:'Proteja a cidade, mas deixe o mistério para trás.',next:'final_safe',effect:{rei:5}}]},
			confronto:{chapter:'Capítulo III · A fenda',title:'O Devorador de Ecos',text:'Você encontra a criatura diante da rachadura. Ela não ataca. Sob a máscara, um coro de vozes: memórias de pessoas que a cidade preferiu esquecer. A fenda está quase engolindo tudo.',choices:[{label:'Atacar com tudo que resta.',detail:'Uma investida pode encerrar a ameaça; custa 10 de energia.',next:'final_fight',cost:{rei:10},effect:{hp:-15,xp:1}},{label:'Baixar a arma e ouvir as vozes.',detail:'Compreenda antes de julgar.',next:'final_listen',effect:{rei:-5,xp:1}}]},
			portal:{chapter:'Capítulo IV · Além do véu',title:'O outro lado responde',text:'A passagem se abre. Do outro lado há um jardim de memórias suspensas e uma figura feita de centenas de rostos esquecidos. “Não quero destruir seu mundo”, diz ela. “Só quero que alguém se lembre.”',choices:[{label:'Prometer que as histórias serão lembradas.',detail:'Faça um pacto entre os mundos.',next:'final_listen',effect:{xp:1}},{label:'Oferecer sua arma como selo.',detail:'Encerre a passagem, mas sacrifique seu poder.',next:'final_seal',effect:{hp:-10,weapon:'Fragmento do selo'}}]},
			final_safe:{chapter:'Desfecho · A cidade desperta',title:'Uma porta fechada',text:'Nara traça um círculo de luz e sela a passagem. A estação está salva, mas milhares de pessoas sonham com nomes que nunca conheceram. A fenda se foi — por enquanto.',ending:'Final: Guardião do Limiar · Você protegeu o presente. As vozes ainda aguardam alguém que as escute.',choices:[{label:'Continuar para o capítulo bônus.',detail:'Uma nova pista surge depois da tempestade.',next:'epilogue'}]},
			final_fight:{chapter:'Desfecho · A cidade desperta',title:'Vitória sem silêncio',text:'Sua arma corta a máscara e a criatura se desfaz em poeira luminosa. A fenda fecha com um estrondo. Nara recolhe um fragmento: dentro dele, ainda há uma voz chamando por alguém.',ending:'Final: Lâmina da Cidade · A ameaça terminou, mas força não responde a todas as perguntas.',choices:[{label:'Continuar para o capítulo bônus.',detail:'Uma nova pista surge depois da tempestade.',next:'epilogue'}]},
			final_listen:{chapter:'Desfecho · A cidade desperta',title:'O nome de cada estrela',text:'Você escuta até reconhecer as histórias escondidas nas vozes. Nara registra cada nome na lanterna. O Devorador se ajoelha, e a fenda se fecha, transformando a chuva em pequenas estrelas.',ending:'Final: Arquivista das Almas · Sua coragem venceu ao dar lugar a quem havia sido esquecido.',choices:[{label:'Continuar para o capítulo bônus.',detail:'Uma nova pista surge depois da tempestade.',next:'epilogue'}]},
			final_seal:{chapter:'Desfecho · A cidade desperta',title:'O último brilho',text:'Sua arma se desfaz em fios de luz e costura a rachadura. O silêncio volta à estação. Nara promete guardar o fragmento que restou; uma parte de você ficou do outro lado.',ending:'Final: Selo Vivo · Você salvou os dois mundos ao custo do poder que acabara de encontrar.',choices:[{label:'Continuar para o capítulo bônus.',detail:'Uma nova pista surge depois da tempestade.',next:'epilogue'}]},
			epilogue:{chapter:'Capítulo V · O que ficou',title:'Três sinais na chuva',text:'Uma semana depois, Kurohama tenta voltar à rotina. Nara chega com a lanterna acesa: três sinais apareceram no mapa, todos ligados a lembranças que ainda não foram devolvidas. Sob a estação, um pulso responde ao seu nome.',choices:[{label:'Levar os nomes ao Arquivo Municipal.',detail:'Descubra quem a cidade tentou esquecer.',next:'epilogue_archive',effect:{ally:'Nara',xp:1}},{label:'Seguir o pulso sob os trilhos.',detail:'Desça até a parte mais antiga de Kurohama.',next:'epilogue_depth',effect:{rei:-5,xp:1}}]},
			epilogue_archive:{chapter:'Capítulo V · As páginas perdidas',title:'Um nome por página',text:'No arquivo, cada nome apagado faz uma gaveta tremer. Você e Nara encontram registros de uma antiga equipe que protegia a cidade antes da estação existir. O último documento traz um aviso: “O véu não se rompeu. Alguém o abriu.”',ending:'Final bônus: Guardião das Memórias · Agora Kurohama sabe que sua história ainda está incompleta.',choices:[]},
			epilogue_depth:{chapter:'Capítulo V · Sob a estação',title:'A cidade sob a cidade',text:'Os trilhos terminam diante de uma porta de pedra. O pulso vem de uma bússola sem ponteiro, presa a um mapa de túneis que não existem. Quando Nara toca o papel, uma nova luz desperta ao norte.',ending:'Final bônus: Cartógrafo do Véu · Você encontrou o próximo caminho antes que ele encontrasse a cidade.',choices:[]}
		};
		function update(){document.getElementById('hpText').textContent=state.hp+'/100';document.getElementById('reiText').textContent=state.rei+'/100';document.getElementById('xpText').textContent=state.xp;document.getElementById('hpBar').style.width=state.hp+'%';document.getElementById('reiBar').style.width=state.rei+'%';document.getElementById('xpBar').style.width=Math.min(100,state.xp*25)+'%';document.getElementById('race').innerHTML=state.race?'<span class="tag">'+state.race+'</span>':'<span class="tag">Ainda não escolhida</span>';document.getElementById('weapon').textContent=state.weapon||'Adormecida';document.getElementById('allies').innerHTML=state.allies.length?state.allies.map(x=>'<span class="tag">'+x+'</span>').join(''):'<span class="tag">Ninguém ainda</span>';document.getElementById('feed').innerHTML=state.log.slice(-5).reverse().map(x=>'<p>· '+x+'</p>').join('')||'<p>Suas escolhas aparecerão aqui.</p>'}
		function show(id){const s=scenes[id];document.getElementById('chapter').textContent=s.chapter;document.getElementById('title').textContent=s.title;document.getElementById('prose').textContent=s.text;document.getElementById('ending').textContent=s.ending||'';const box=document.getElementById('choices');box.replaceChildren();s.choices.forEach(c=>{const b=document.createElement('button');b.className='choice';const ok=!c.cost||Object.entries(c.cost).every(([k,v])=>state[k]>=v);b.disabled=!ok;const strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=c.label;small.textContent=c.detail+(ok?'':' · energia insuficiente');b.append(strong,small);b.onclick=()=>choose(c);box.append(b)})}
		function choose(c){if(c.cost&&!Object.entries(c.cost).every(([k,v])=>state[k]>=v))return;if(c.cost)for(const[k,v]of Object.entries(c.cost))state[k]-=v;if(c.effect)for(const[k,v]of Object.entries(c.effect)){if(k==='ally'){if(!state.allies.includes(v))state.allies.push(v)}else if(k==='race'||k==='weapon')state[k]=v;else state[k]=Math.max(0,Math.min(k==='xp'?99:100,state[k]+v))}state.log.push(c.label.replace(/[“”]/g,''));update();show(c.next)}
		document.getElementById('reset').onclick=()=>{state=fresh();update();show('start')};update();show('start');

(()=>{
			const saveKey='veu-partido-save';let currentScene='start';
			const originalChoose=choose;
			choose=function(choice){originalChoose(choice);currentScene=choice.next;try{localStorage.setItem(saveKey,JSON.stringify({state,scene:currentScene}))}catch{}};
			const resetButton=document.getElementById('reset');
			const originalReset=resetButton.onclick;
			resetButton.onclick=()=>{originalReset();currentScene='start';try{localStorage.removeItem(saveKey)}catch{}};
			try{
				const saved=JSON.parse(localStorage.getItem(saveKey));
				if(saved&&scenes[saved.scene]&&saved.state&&typeof saved.state==='object'){
					const value=saved.state,initial=fresh();
					const bounded=(number,min,max,fallback)=>Number.isFinite(number)?Math.max(min,Math.min(max,number)):fallback;
					state={hp:bounded(value.hp,0,100,initial.hp),rei:bounded(value.rei,0,100,initial.rei),xp:bounded(value.xp,0,99,initial.xp),race:typeof value.race==='string'?value.race:'',weapon:typeof value.weapon==='string'?value.weapon:'',allies:Array.isArray(value.allies)?value.allies.filter(item=>typeof item==='string'):[],log:Array.isArray(value.log)?value.log.filter(item=>typeof item==='string'):[]};
					currentScene=saved.scene;update();show(currentScene);
				}
			}catch{try{localStorage.removeItem(saveKey)}catch{}}
		})();
